// <auto-generated />
using System;
using HackathonTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackathonTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421185700_AddMasterTables")]
    partial class AddMasterTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HackathonTest.Models.DropDownMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DropdownMasters");
                });

            modelBuilder.Entity("HackathonTest.Models.NominationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentDuns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapacityBlockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelLocId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelLocProp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DelQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DelRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownIdProp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FuelPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GisbStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NomQuickResponseDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NomSubmittedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomTrackingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pipeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PkgId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuantityTypeIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecLocId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecLocProp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RecQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SchedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shipper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperSpecificId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpIdProp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NominationRecords");
                });

            modelBuilder.Entity("HackathonTest.Models.PipelineMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PipelineMasters");
                });

            modelBuilder.Entity("HackathonTest.Models.ShipperMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShipperMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
